-- Initialization of the database
/* Creation of the required tables */
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    telegram_id BIGINT UNIQUE NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE event_types (
    id SERIAL PRIMARY KEY,
    title VARCHAR(64) NOT NULL UNIQUE,
    description TEXT DEFAULT '' NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    is_public BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    owner_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,

    CHECK(is_public or not is_default)
);

CREATE TABLE events (
    id SERIAL PRIMARY KEY,

    title VARCHAR(64) NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    duration INTERVAL DEFAULT NULL,
    event_type_id INTEGER REFERENCES event_types(id) ON DELETE CASCADE,
    
    creator_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CHECK (duration > INTERVAL '0 seconds')
);

CREATE TABLE subscriptions (
    id SERIAL PRIMARY KEY,

    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    event_type_id INTEGER REFERENCES event_types(id) ON DELETE CASCADE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UNIQUE(user_id, event_type_id)
);


/* Defaults */
INSERT INTO event_types(title, description, is_default)
    VALUES('Default', '', TRUE);


/* Indexes. users.telegram_id needs no index since it's implicitly generated by UNIQUE constraint */
CREATE INDEX subscriptions__event_type_idx ON subscriptions (event_type_id);

CREATE INDEX events__starts_at_idx ON events (starts_at);
CREATE INDEX events__event_type_id_idx ON events (event_type_id);


/* Functions */
CREATE FUNCTION add_default_subscription__trigger()
RETURNS TRIGGER AS $$
DECLARE
    new_event_type_id INT;
BEGIN
    -- Subcribe to the default ones
    INSERT INTO subscriptions(user_id, event_type_id)
        SELECT NEW.id, id
        FROM event_types
        WHERE is_default = TRUE AND is_public = TRUE;

    INSERT INTO event_types(title, description, is_public, owner_user_id)
        VALUES(
            'Personal ' || NEW.id::TEXT,
            'Personal event type for user with Telegram ID ' || NEW.telegram_id::TEXT,
            FALSE, NEW.id
        )
    RETURNING id INTO new_event_type_id;

    INSERT INTO subscriptions(user_id, event_type_id)
        VALUES(NEW.id, new_event_type_id);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


/* Triggers */
CREATE TRIGGER add_default_subscription__trigger
    AFTER INSERT ON users
    FOR EACH ROW
    EXECUTE FUNCTION add_default_subscription__trigger();
